import {_electron as electron,chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {readConfig} from '../electron/storage.cjs';
const root=path.resolve('.'),profile=await fs.mkdtemp(path.join(os.tmpdir(),'pipeline-desk-groups-'));
const shots=path.join(root,'.impeccable/review');await fs.mkdir(shots,{recursive:true});
const env={...process.env,PIPELINE_DESK_PROFILE:profile,PIPELINE_DESK_TEST:'1'};delete env.ELECTRON_RUN_AS_NODE;
let app,browser;const errors=[];
try{
  app=await electron.launch({args:[root],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
  await page.locator('.pipeline-card').first().waitFor();
  await app.evaluate(({shell})=>{
    globalThis.membersChanged=false;globalThis.openedUrls=[];shell.openExternal=async url=>{globalThis.openedUrls.push(url);};
    globalThis.fetch=async url=>{
      const u=new URL(url),route=u.pathname;
      const project=id=>({id,path:{42:'supply-demand-backend',43:'supply-demand-frontend',44:'api-gateway',45:'new-service'}[id],namespace:{full_path:'AEDON / platform'},web_url:`https://git.groups.invalid/team/${id}`});
      const group=id=>({id,name:id===10?'Platform':'Services',full_path:id===10?'team':'team/services',parent_id:id===10?null:10,web_url:`https://git.groups.invalid/groups/${id}`});
      let body;
      if(route.endsWith('/user'))body={username:'fixture'};
      else if(route.endsWith('/groups'))body=[group(10),group(11)];
      else if(/\/groups\/\d+$/.test(route))body=group(Number(route.split('/').at(-1)));
      else if(/\/groups\/\d+\/projects$/.test(route))body=(route.includes('/10/')?[42,43,globalThis.membersChanged?45:44]:[43]).map(project);
      else if(route.endsWith('/projects'))body=[42,43,44].map(project);
      else if(/\/projects\/\d+$/.test(route))body=project(Number(route.split('/').at(-1)));
      else if(route.endsWith('/pipelines'))body=[{id:99,status:'success'}];
      else if(route.endsWith('/pipelines/99'))body={id:99,status:'success',ref:'main',sha:'abcdef123',duration:42};
      else if(route.endsWith('/jobs'))body=[{id:1,name:'test',stage:'test',status:'success'}];
      else if(route.endsWith('/bridges'))body=[];
      else return new Response('{}',{status:404});
      return new Response(JSON.stringify(body));
    };
  });
  await page.locator('#settings-button').click();await page.locator('#edit-server').click();
  await page.locator('#host-input').fill('https://git.groups.invalid');await page.locator('#token-input').fill('fixture-only');await page.locator('#connect-submit').click();
  await page.locator('#add-dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');
  await page.locator('#new-group-button').click();await page.locator('#group-name').fill('Работа');
  await page.locator('#group-catalog input[value="42"]').check();await page.locator('#group-catalog input[value="43"]').check();
  await page.locator('#save-group').click();await page.locator('#group-dialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('.pipeline-card').count(),2);
  await page.getByRole('button',{name:'Компактный вид',exact:true}).click();
  assert.equal(await page.locator('.compact-project').count(),2);
  await page.screenshot({path:path.join(shots,'groups-overview.png'),animations:'disabled'});
  const widgetCreated=app.waitForEvent('window');await page.getByRole('button',{name:'Закрепить группу Работа',exact:true}).click();
  const widget=await widgetCreated;await widget.locator('.compact-project').first().waitFor();
  assert.equal(await widget.locator('.compact-project').count(),2);
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).isAlwaysOnTop()),true);
  await widget.screenshot({path:path.join(shots,'group-widget.png'),animations:'disabled'});
  await widget.getByRole('button',{name:'Открыть репозиторий supply-demand-backend',exact:true}).click();
  assert.equal((await app.evaluate(()=>globalThis.openedUrls)).at(-1),'https://git.groups.invalid/team/42');
  await widget.getByLabel('Вид виджета',{exact:true}).selectOption('full');await widget.locator('.pipeline-card').first().waitFor();
  await widget.getByLabel('Вид виджета',{exact:true}).selectOption('compact');await widget.locator('.compact-project').first().waitFor();
  await page.locator('#new-group-button').click();await page.locator('[data-group-mode="gitlab"]').click();
  await page.locator('#group-catalog input[value="10"]').check();
  await page.screenshot({path:path.join(shots,'group-picker.png'),animations:'disabled'});
  await page.locator('#save-group').click();await page.locator('#group-dialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('.compact-project').count(),3);
  await page.locator('#new-group-button').click();await page.locator('#group-name').fill('Всё вместе');await page.locator('[data-group-mode="local"]').click();
  await page.locator('#group-catalog input').nth(0).check();await page.locator('#group-catalog input').nth(1).check();
  await page.locator('[data-group-mode="gitlab"]').click();await page.locator('#group-catalog input[value="11"]').check();
  await page.locator('#save-group').click();await page.locator('#group-dialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('.compact-project').count(),3);
  const mergedCreated=app.waitForEvent('window');await page.getByRole('button',{name:'Закрепить группу Всё вместе',exact:true}).click();
  const mergedWidget=await mergedCreated;await mergedWidget.locator('.compact-project').first().waitFor();
  await app.evaluate(()=>{globalThis.membersChanged=true;});await page.locator('#refresh-button').click();
  await mergedWidget.locator('.compact-project[data-project="45:"]').waitFor();
  assert.equal(await mergedWidget.locator('.compact-project[data-project="44:"]').count(),0);
  assert.equal(await mergedWidget.locator('.compact-project').count(),3);
  // Individual widgets become short native windows and retain pin behavior.
  const soloCreated=app.waitForEvent('window');await page.getByRole('button',{name:'Закрепить виджет supply-demand-backend',exact:true}).click();
  const solo=await soloCreated;await solo.locator('.pipeline-card').waitFor();await solo.getByLabel('Вид виджета',{exact:true}).selectOption('compact');
  await solo.locator('.solo-summary').waitFor();
  const shortWindow=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>new URL(w.webContents.getURL()).searchParams.get('widget')==='42:').getBounds());
  assert.ok(shortWindow.height<=120);
  await solo.screenshot({path:path.join(shots,'compact-widget.png'),animations:'disabled'});
  const stored=readConfig(profile);
  assert.equal(stored.groups.length,3);assert.equal(stored.widgets['42:'].compact,true);
  const snapshot=await page.evaluate(()=>window.desk.snapshot());
  await app.close();app=null;
  app=await electron.launch({args:[root],env});const restored=await app.firstWindow();
  await restored.locator('.compact-project').first().waitFor();
  assert.equal((await restored.evaluate(()=>window.desk.snapshot())).groups.length,3);
  await restored.waitForFunction(()=>Object.keys(window.desk).includes('saveGroup'));
  const nativeWindows=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({key:new URL(w.webContents.getURL()).searchParams.get('widget'),pinned:w.isAlwaysOnTop(),height:w.getBounds().height})));
  assert.equal(nativeWindows.find(w=>w.key==='42:').height<=120,true);
  assert.ok(nativeWindows.filter(w=>w.key).every(w=>w.pinned));
  await app.close();app=null;
  browser=await chromium.launch({channel:'msedge',headless:true});const narrow=await browser.newPage({viewport:{width:390,height:844}});
  await narrow.addInitScript(state=>{window.desk={snapshot:async()=>state,onUpdate:()=>{}};localStorage.setItem('desk-view','compact');localStorage.setItem('desk-group',state.groups[2].key);},snapshot);
  await narrow.goto('http://127.0.0.1:4317/ui/index.html');await narrow.locator('.compact-project').first().waitFor();
  await narrow.screenshot({path:path.join(shots,'groups-narrow.png'),animations:'disabled'});
  assert.equal(await narrow.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: manual groups, GitLab groups/subgroups, merge deduplication, live membership, native group pin, repository links, compact rows and windows, restart persistence, narrow layout.');
}finally{if(app)await app.close().catch(()=>{});if(browser)await browser.close();}
