import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {readConfig} from '../electron/storage.cjs';
const root=path.resolve('.'),profile=await fs.mkdtemp(path.join(os.tmpdir(),'pipeline-desk-notifications-'));
const env={...process.env,PIPELINE_DESK_PROFILE:profile,PIPELINE_DESK_TEST:'1'};delete env.ELECTRON_RUN_AS_NODE;
const errors=[];let app;
async function launch(status='running'){
  app=await electron.launch({args:[path.join(root,'tests/fixtures/notifications-main.cjs')],env:{...env,NOTIFICATION_FIXTURE_STATUS:status}});
  const page=(await app.windows()).find(w=>!w.url().includes('widget='))||await app.firstWindow();
  page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>!!window.desk);
  return page;
}
const bell=(page,key)=>page.locator(`[data-action="notifications"][data-key="${key}"]`).first();
try{
  let page=await launch();
  await page.evaluate(()=>window.desk.connect({host:'https://git.notifications.invalid',token:'notification-fixture-token'}));
  await page.evaluate(()=>window.desk.addProjects([42,43]));
  const group=await page.evaluate(()=>window.desk.saveGroup({name:'Работа',projectKeys:['42:','43:']}));
  await page.locator(`[data-action="select-group"][data-key="${group.key}"]`).click();
  await bell(page,'42:').click();await page.waitForFunction(()=>document.querySelector('[data-action="notifications"][data-key="42:"]').getAttribute('aria-pressed')==='true');
  await bell(page,group.key).focus();await page.keyboard.press('Space');
  await page.waitForFunction(key=>document.activeElement?.dataset.key===key&&document.activeElement?.getAttribute('aria-pressed')==='true',group.key);
  assert.equal((await readConfig(profile)).notifications[group.key],true);
  assert.equal(await app.evaluate(()=>globalThis.toasts.length),0);
  const created=app.waitForEvent('window');await page.evaluate(key=>window.desk.openWidget(key),group.key);
  const widget=await created;await bell(widget,group.key).waitFor();
  assert.equal(await bell(widget,group.key).getAttribute('aria-pressed'),'true');
  assert.equal(await bell(widget,'43:').getAttribute('aria-pressed'),'false');
  assert.ok((await bell(widget,'43:').getAttribute('class')).includes('via-group'));
  await app.evaluate(()=>{globalThis.pipelineStatus='failed';});await page.evaluate(()=>window.desk.refresh());
  assert.equal(await app.evaluate(()=>globalThis.toasts.length),2);
  const message=await app.evaluate(()=>({title:globalThis.toasts[0].title,body:globalThis.toasts[0].body}));
  assert.match(message.title,/Ошибка/);assert.equal(message.body,'Работа · #100 · main');
  await app.evaluate(()=>globalThis.toasts[0].emit('click'));
  assert.equal((await app.evaluate(()=>globalThis.openedUrls))[0],'https://git.notifications.invalid/team/backend/-/pipelines/100');
  await page.evaluate(()=>window.desk.refresh());assert.equal(await app.evaluate(()=>globalThis.toasts.length),2);
  const shots=path.join(root,'.impeccable/review');await fs.mkdir(shots,{recursive:true});
  await page.screenshot({path:path.join(shots,'notifications-overview.png'),animations:'disabled'});
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).setBounds({width:330}));
  await widget.screenshot({path:path.join(shots,'notifications-widget-330.png'),animations:'disabled'});
  assert.equal(await widget.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('[data-action="detail"][data-key="42:"]').first().click();
  const detailBell=page.locator('#detail-content [data-action="notifications"]');
  await detailBell.focus();await page.keyboard.press('Space');
  await page.waitForFunction(()=>document.activeElement?.matches('#detail-content [data-action="notifications"][aria-pressed="false"]'));
  await page.keyboard.press('Space');
  await page.waitForFunction(()=>document.activeElement?.matches('#detail-content [data-action="notifications"][aria-pressed="true"]'));
  await page.keyboard.press('Escape');
  const config=readConfig(profile);assert.ok(config.token);assert.equal(config.projects.length,2);
  await app.close();app=null;
  page=await launch('failed');await page.evaluate(()=>window.desk.refresh());
  assert.equal(await bell(page,group.key).getAttribute('aria-pressed'),'true');
  assert.equal(await app.evaluate(()=>globalThis.toasts.length),0);
  await app.evaluate(()=>{globalThis.pipelineStatus='success';});await page.evaluate(()=>window.desk.refresh());
  assert.equal(await app.evaluate(()=>globalThis.toasts.length),2);
  await page.evaluate(key=>window.desk.setNotifications({key,enabled:false}),group.key);
  await page.evaluate(()=>window.desk.setNotifications({key:'42:',enabled:false}));
  await app.evaluate(()=>{globalThis.pipelineStatus='canceled';});await page.evaluate(()=>window.desk.refresh());
  assert.equal(await app.evaluate(()=>globalThis.toasts.length),2);
  await assert.rejects(page.evaluate(()=>window.desk.setNotifications({key:'missing',enabled:true})),/не найдены/);
  await page.evaluate(()=>window.desk.disconnect());assert.deepEqual(readConfig(profile).notifications,{});
  assert.deepEqual(errors,[]);
  console.log('PASS: project/group bells, native notification payload/click, overlap deduplication, 330px widget, SQLite restart, status changes and opt-out.');
}finally{if(app)await app.close().catch(()=>{});}
