import {_electron as electron} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {demoProjects} from '../ui/demo.js';
import {readConfig,DATABASE_NAME} from '../electron/storage.cjs';
const env={...process.env,PIPELINE_DESK_PROFILE:await fs.mkdtemp(path.join(os.tmpdir(),'pipeline-desk-packaged-')),PIPELINE_DESK_TEST:'1'};
delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:path.resolve('release/PipelineDesk-win32-x64/PipelineDesk.exe'),args:[],env});
try{
  const page=await app.firstWindow();
  await page.locator('.pipeline-card').first().waitFor();
  assert.equal(await page.locator('.pipeline-card').count(),6);
  assert.equal(await app.evaluate(({app})=>app.isPackaged),true);
  assert.equal(await page.evaluate(async()=> (await window.desk.snapshot()).desktop),true);
  assert.equal((await fs.readFile(path.join(env.PIPELINE_DESK_PROFILE,DATABASE_NAME))).subarray(0,16).toString(),'SQLite format 3\0');
  assert.equal(await page.evaluate(()=>typeof window.desk.setNotifications),'function');
  assert.deepEqual(await page.evaluate(async()=>(await window.desk.snapshot()).notifications),{});
  assert.equal(readConfig(env.PIPELINE_DESK_PROFILE).interval,15000);
  await page.locator('#settings-button').click();
  await page.locator('.setup-details summary').click();
  await page.locator('#interval-input').selectOption('5000');
  await page.locator('#interval-input').selectOption('10000');
  await page.evaluate(()=>window.desk.settings({interval:5000}));
  assert.equal(readConfig(env.PIPELINE_DESK_PROFILE).interval,5000);
  await page.keyboard.press('Escape');
  await page.locator('#settings-dialog').waitFor({state:'hidden'});
  const opened=app.waitForEvent('window');
  await page.getByRole('button',{name:'Закрепить виджет web-app-backend',exact:true}).click();
  const widget=await opened;await widget.locator('.pipeline-card').waitFor();
  assert.equal(await widget.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),true);
  await widget.getByLabel('Вид виджета').selectOption('stages');await widget.locator('.solo-summary').waitFor();
  assert.equal(await widget.locator('.stage').count(),4);
  await widget.getByLabel('Вид виджета').selectOption('compact');
  await widget.waitForFunction(()=>document.body.dataset.widgetView==='compact');
  assert.equal(await widget.locator('.stage,.branch-label,.namespace').count(),0);
  assert.equal(readConfig(env.PIPELINE_DESK_PROFILE).widgets['demo-0'].view,'compact');
  const groupOpened=app.waitForEvent('window');await page.evaluate(()=>window.desk.openWidget('demo-group-platform'));
  const group=await groupOpened;await group.locator('.pipeline-stage-block').first().waitFor();
  assert.equal(await group.locator('.stage').count(),8);
  const projects=demoProjects(),key='demo-group-platform';
  await app.evaluate(({BrowserWindow},snapshot)=>{
    BrowserWindow.getAllWindows().find(w=>new URL(w.webContents.getURL()).searchParams.get('widget')===snapshot.groups[0].key).webContents.send('desk:update',snapshot);
  },{connected:true,projects,groups:[{key,name:'Six projects',memberKeys:projects.map(p=>p.key),sources:[]}],widgets:[key],widgetOptions:{[key]:{view:'full'}},interval:15000});
  await group.locator('.pipeline-card').first().waitFor();
  assert.equal(await group.locator('.pipeline-card').count(),6);
  assert.equal(await group.locator('.pipeline-card').evaluateAll(cards=>cards.every(card=>card.querySelector('.card-bottom').getBoundingClientRect().bottom<=card.getBoundingClientRect().bottom+1)),true,'Packaged detailed cards must not clip their content');
  assert.equal(await group.locator('.group-body').evaluate(el=>el.scrollHeight>el.clientHeight),true);
  console.log('PASS: packaged Windows EXE, faster polling options, SQLite storage, sandboxed preload, native widget, three views, six detailed cards without clipping.');
}finally{await app.close();}
