import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const profile=await fs.mkdtemp(path.join(os.tmpdir(),'pipeline-desk-test-'));
const shots=path.join(root,'.impeccable/review');await fs.mkdir(shots,{recursive:true});
const env={...process.env,PIPELINE_DESK_PROFILE:profile,PIPELINE_DESK_TEST:'1'};delete env.ELECTRON_RUN_AS_NODE;
let app;
const errors=[];
async function launch(){
  app=await electron.launch({args:[root],env});
  const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
  await page.locator('.pipeline-card').first().waitFor();return page;
}
try{
  const page=await launch();
  assert.equal(await page.locator('.pipeline-card').count(),6);
  await page.screenshot({path:path.join(shots,'desktop.png')});
  await page.getByRole('button',{name:'Ошибки'}).click();assert.equal(await page.locator('.pipeline-card').count(),1);
  await page.getByRole('button',{name:'В работе'}).click();assert.equal(await page.locator('.pipeline-card').count(),2);
  await page.getByRole('button',{name:'Все',exact:false}).first().click();
  await page.getByRole('button',{name:'Список',exact:true}).click();assert.ok(await page.locator('#projects').evaluate(el=>el.classList.contains('list-view')));
  await page.getByRole('button',{name:'Карточки',exact:true}).click();
  await page.getByRole('button',{name:'Пайплайн 8553',exact:true}).click();
  await page.locator('#detail-dialog').waitFor({state:'visible'});assert.equal(await page.locator('.job-row').count(),4);
  await page.keyboard.press('Escape');
  const created=app.waitForEvent('window');
  await page.getByRole('button',{name:'Закрепить виджет supply-demand-backend',exact:true}).click();
  const widget=await created;await widget.locator('.pipeline-card').waitFor();
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).isAlwaysOnTop()),true);
  await widget.screenshot({path:path.join(shots,'widget.png')});
  assert.equal(await widget.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),true);
  await widget.getByRole('button',{name:'Открепить',exact:true}).click();
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).isAlwaysOnTop()),false);
  await widget.getByRole('button',{name:'Поверх окон',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(shots,'mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.setViewportSize({width:1100,height:790});
  await page.getByRole('button',{name:'Светлая тема',exact:true}).click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  await page.screenshot({path:path.join(shots,'light.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Тёмная тема',exact:true}).click();
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.status-symbol.running').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await app.close();
  const restored=await launch();
  await restored.waitForFunction(()=>document.querySelector('[data-action="pin"]')?.getAttribute('aria-pressed')==='true');
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),2);
  await app.evaluate(()=>{
    globalThis.fakeStatus='running';
    globalThis.fetch=async(url,options)=>{
      if(options.headers['PRIVATE-TOKEN']!=='test-token-never-real')return new Response('{}',{status:401});
      if(globalThis.fakeStatus==='offline')throw new Error('offline');
      const route=new URL(url).pathname;
      let body;
      if(route.endsWith('/user'))body={username:'test-user'};
      else if(route.endsWith('/projects'))body=[];
      else if(route.endsWith('/projects/group%2Fbackend'))body={id:42,path:'backend',namespace:{full_path:'group'},web_url:'https://git.example/group/backend'};
      else if(route.endsWith('/pipelines'))body=[{id:99,status:globalThis.fakeStatus,web_url:'https://git.example/group/backend/-/pipelines/99'}];
      else if(route.endsWith('/pipelines/99'))body={id:99,status:globalThis.fakeStatus,ref:'main',sha:'abcdef1234',duration:42,web_url:'https://git.example/group/backend/-/pipelines/99'};
      else if(route.endsWith('/jobs'))body=[{id:1,name:'test',stage:'test',status:'success'},{id:2,name:'deploy',stage:'deploy',status:globalThis.fakeStatus}];
      else if(route.endsWith('/bridges'))body=[];
      else return new Response('{}',{status:404});
      return new Response(JSON.stringify(body));
    };
  });
  await restored.getByRole('button',{name:'Настройки',exact:true}).click();
  await restored.locator('#edit-server').click();
  await restored.locator('#host-input').fill('https://git.example');
  await restored.locator('#token-input').fill('wrong-token');
  await restored.locator('#connect-submit').click();
  await restored.locator('#settings-error').filter({hasText:'Токен недействителен'}).waitFor();
  await restored.locator('#token-input').fill('test-token-never-real');
  await restored.locator('#connect-submit').click();
  await restored.locator('#add-dialog').waitFor({state:'visible'});
  await restored.locator('[data-picker-mode="manual"]').click();
  await restored.locator('#project-input').fill('group/backend');
  await restored.locator('#branch-input').fill('main');
  await restored.locator('#add-form button[type="submit"]').click();
  await restored.locator('.pipeline-card[data-status="running"]').waitFor();
  assert.equal(await restored.locator('.pipeline-card').count(),1);
  const saved=await fs.readFile(path.join(profile,'settings.json'),'utf8');
  assert.equal(saved.includes('test-token-never-real'),false);
  assert.equal(JSON.parse(saved).projects[0].id,42);
  await app.evaluate(()=>{globalThis.fakeStatus='failed';});
  await restored.getByRole('button',{name:'Обновить',exact:true}).click();
  await restored.locator('.pipeline-card[data-status="failed"]').waitFor();
  await app.evaluate(()=>{globalThis.fakeStatus='offline';});
  await restored.getByRole('button',{name:'Обновить',exact:true}).click();
  await restored.locator('.card-error').filter({hasText:'GitLab недоступен'}).waitFor();
  assert.ok(await restored.locator('.card-error').textContent());
  const blocked=await restored.evaluate(async()=>{try{await window.desk.openExternal('https://evil.example');return false;}catch{return true;}});assert.equal(blocked,true);
  assert.deepEqual(errors,[]);
  console.log('PASS: filters, details, list, native pin/unpin, window restore, narrow layout, theme, reduced motion, connection errors, project, status refresh, offline cache, protected token, external URL restriction.');
  console.log('Screenshots: '+shots);
}finally{if(app)await app.close().catch(()=>{});}
