import {_electron as electron,chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {demoProjects} from '../ui/demo.js';
import {readConfig} from '../electron/storage.cjs';

const root=path.resolve('.'),profile=await fs.mkdtemp(path.join(os.tmpdir(),'pipeline-desk-views-'));
const shots=path.join(root,'.impeccable/review');await fs.mkdir(shots,{recursive:true});
const env={...process.env,PIPELINE_DESK_PROFILE:profile,PIPELINE_DESK_TEST:'1'};delete env.ELECTRON_RUN_AS_NODE;
let app,browser;const errors=[];
try{
  app=await electron.launch({args:[root],env});const page=await app.firstWindow();
  await page.locator('.pipeline-card').first().waitFor();
  const created=app.waitForEvent('window');await page.evaluate(()=>window.desk.openWidget('demo-group-platform'));
  const widget=await created;widget.on('pageerror',e=>errors.push(e.message));
  await widget.locator('.pipeline-stage-block').first().waitFor();
  assert.equal(await widget.getByLabel('Вид виджета').inputValue(),'stages');
  assert.equal(await widget.locator('.stage').count(),8);
  assert.equal(await widget.locator('.namespace,.branch-label').count(),0);
  await widget.getByLabel('Вид виджета').selectOption('compact');
  await widget.waitForFunction(()=>document.body.dataset.widgetView==='compact');
  assert.equal(await widget.locator('.stage').count(),0);
  assert.ok(await widget.locator('.compact-project').first().evaluate(el=>el.getBoundingClientRect().height<=40));
  await widget.getByLabel('Вид виджета').selectOption('full');
  await widget.locator('.pipeline-card').first().waitFor();
  assert.equal(await widget.locator('.stage').count(),8);
  await widget.getByLabel('Вид виджета').selectOption('stages');
  await widget.locator('.pipeline-stage-block').first().waitFor();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).setSize(440,380));
  const resizedHeight=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).getBounds().height);
  await widget.getByLabel('Вид виджета').selectOption('compact');
  await widget.waitForFunction(()=>document.body.dataset.widgetView==='compact');
  await widget.getByLabel('Вид виджета').selectOption('stages');
  await widget.locator('.pipeline-stage-block').first().waitFor();
  const restoredHeight=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).getBounds().height);
  assert.ok(Math.abs(restoredHeight-resizedHeight)<=2,'Restores the stage-view height within Windows fractional-DPI rounding');
  const stored=readConfig(profile);
  assert.equal(stored.widgets['demo-group-platform'].view,'stages');
  await app.close();app=null;
  app=await electron.launch({args:[root],env});await app.firstWindow();
  await app.evaluate(async()=>{await new Promise(resolve=>setTimeout(resolve,200));});
  const restored=(await app.windows()).find(w=>w.url().includes('widget='));assert.ok(restored);
  await restored.locator('.pipeline-stage-block').first().waitFor();
  assert.equal(await restored.getByLabel('Вид виджета').inputValue(),'stages');
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('widget=')).isAlwaysOnTop()),true);
  await app.close();app=null;

  const projects=demoProjects().slice(0,3).map(p=>({...p,demo:false,webUrl:'https://git.fixture.invalid/project'}));
  const key='group:fixture';
  const snapshot={desktop:true,connected:true,host:'https://git.fixture.invalid',projects,groups:[{key,name:'Мои проекты',memberKeys:projects.map(p=>p.key),sources:[]}],widgets:[key],widgetOptions:{[key]:{view:'stages'}},interval:15000};
  browser=await chromium.launch({channel:'msedge',headless:true});
  const fixture=await browser.newPage({viewport:{width:440,height:378}});fixture.on('pageerror',e=>errors.push(e.message));
  await fixture.addInitScript(state=>{
    localStorage.setItem('desk-theme','light');
    window.fixtureState=state;
    window.desk={snapshot:async()=>window.fixtureState,onUpdate:fn=>{window.pushFixture=fn;},setWidgetView:async view=>{state.widgetOptions['group:fixture'].view=view;window.pushFixture(state);}};
  },snapshot);
  await fixture.goto('http://127.0.0.1:4317/ui/index.html?widget=group%3Afixture');
  await fixture.locator('.pipeline-stage-block').first().waitFor();
  await fixture.screenshot({path:path.join(shots,'widget-stages-light.png'),animations:'disabled'});
  await fixture.evaluate(()=>document.documentElement.dataset.theme='dark');
  await fixture.screenshot({path:path.join(shots,'widget-stages-dark.png'),animations:'disabled'});
  await fixture.getByLabel('Вид виджета').selectOption('compact');
  await fixture.setViewportSize({width:440,height:180});
  await fixture.screenshot({path:path.join(shots,'widget-rows.png'),animations:'disabled'});
  await fixture.getByLabel('Вид виджета').selectOption('stages');
  await fixture.setViewportSize({width:330,height:560});
  await fixture.evaluate(()=>{
    const p=window.fixtureState.projects[0];
    p.stages=['quality','build','migrations','deploy','integration-tests','production_database_migration','smoke tests after deployment','cleanup'].map((name,i)=>({name,status:i<5?'success':i===5?'running':'pending',jobs:[{id:i,name,status:'success'}]}));
    window.pushFixture(window.fixtureState);
  });
  assert.equal(await fixture.locator('.pipeline-stage-block').first().locator('.stage').count(),8);
  assert.equal(await fixture.locator('.complete-stages .stage>span:last-child').evaluateAll(labels=>labels.every(el=>el.scrollWidth<=el.clientWidth&&el.scrollHeight<=el.clientHeight)),true);
  assert.equal(await fixture.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.group-body').scrollWidth<=document.querySelector('.group-body').clientWidth),true);
  const picker=await fixture.getByLabel('Вид виджета').elementHandle();await picker.focus();
  await fixture.evaluate(()=>window.pushFixture({...window.fixtureState,updating:true}));
  assert.equal(await picker.evaluate(el=>el.isConnected&&document.activeElement===el),true);
  await fixture.screenshot({path:path.join(shots,'widget-stages-narrow.png'),animations:'disabled'});
  await fixture.locator('.stage').first().click();await fixture.locator('#detail-dialog').waitFor({state:'visible'});
  assert.equal(await fixture.locator('.job-stage').count(),8);
  await fixture.mouse.click(2,2);assert.equal(await fixture.locator('#detail-dialog').evaluate(el=>el.open),true);
  await fixture.keyboard.press('Escape');await fixture.locator('#detail-dialog').waitFor({state:'hidden'});
  await fixture.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await fixture.locator('.status-symbol.running').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  assert.deepEqual(errors,[]);
  console.log('PASS: three native views, smaller rows, no subtitle, view and height persistence, all stages, long labels at 330px, refresh preserves picker focus, details, backdrop, reduced motion.');
}finally{if(app)await app.close().catch(()=>{});if(browser)await browser.close();}
